### ISSUE TITLE
documentation is not complete

### ISSUE THREAD

**Issue by gurugeek** [eladnava/koa-mysql#1]
First thank you for providing this package.

I think the minimal example should at least clarify how to so a simple SELECT * query using the package. 
var results = yield db.query('SELECT * FROM `soccer'); doesn't work . The normal methods used and working with with the mysql package do not work. So I think at the bare minimum the example should include example of SELECT, INSERT, UPDATE, DELETE.

**Comment by eladnava** [comment]
Hi @gurugeek,
Thanks for your input.

The code you posted should definitely work, so please check for a connectivity issue to your database:
```
var results = yield db.query('SELECT * FROM `soccer');
```

**Comment by gurugeek** [comment]
hi @eladnava I am using this example https://github.com/bananaappletw/koa2-examples/blob/master/blog/app.js and definitely my query is not working. Is your package just for koa 1 perhaps ?

**Comment by eladnava** [comment]
Hi @gurugeek,
Indeed it's for Koa 1. I'm not entirely sure how Koa 2 could've broken it, unless it doesn't support async/await on "Thunkified" functions.

Consider `node-mysql2` instead, which is a promise-first MySQL library you can use in Koa 2:
https://github.com/sidorares/node-mysql2

```
async function main() {
  // get the client
  const mysql = require('mysql2/promise');
  // create the connection
  const connection = await mysql.createConnection({host:'localhost', user: 'root', database: 'test'});
  // query database
  const [rows, fields] = await connection.execute('SELECT * FROM `table` WHERE `name` = ? AND `age` > ?', ['Morty', 14]);
}
```
